/// Flutter icons UiIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UiIcons
///      fonts:
///       - asset: fonts/UiIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class UiIcons {
  UiIcons._();

  static const _kFontFam = 'UiIcons';
  static const String? _kFontPkg = null;

  static const IconData covid = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faskes = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData peduli_covid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vaccine = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_square = IconData(0xf082, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf08c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
